#!/bin/bash

# ============================================================
# GOOGLE SHEETS API SETUP SCRIPT
# Hướng dẫn chi tiết cài đặt & cấu hình Google Sheets API
# ============================================================

set -e

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}"
cat << "EOF"
╔═══════════════════════════════════════════════════════════╗
║                                                           ║
║         📊 GOOGLE SHEETS API SETUP WIZARD 📊             ║
║                                                           ║
╚═══════════════════════════════════════════════════════════╝
EOF
echo -e "${NC}\n"

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Wizard này sẽ hướng dẫn bạn setup Google Sheets API${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"

# Step 1: Open Google Cloud Console
echo -e "${YELLOW}━━━ BƯỚC 1: Tạo Google Cloud Project ━━━${NC}\n"
echo -e "${CYAN}1.1${NC} Mở Google Cloud Console:"
echo -e "    ${GREEN}https://console.cloud.google.com/${NC}\n"

read -p "$(echo -e ${CYAN}Đã mở Console? [Y/n]: ${NC})" CONFIRM1
if [[ ! $CONFIRM1 =~ ^[Yy]?$ ]]; then
    echo "Vui lòng mở Google Cloud Console để tiếp tục"
    exit 1
fi

echo -e "\n${CYAN}1.2${NC} Tạo Project mới:"
echo -e "    - Click [Select a project] ở top bar"
echo -e "    - Click [NEW PROJECT]"
echo -e "    - Project name: ${GREEN}MIA-Dashboard${NC}"
echo -e "    - Click [CREATE]"
echo ""

read -p "$(echo -e ${CYAN}Đã tạo project? [Y/n]: ${NC})" CONFIRM2

# Step 2: Enable APIs
echo -e "\n${YELLOW}━━━ BƯỚC 2: Enable Google Sheets API ━━━${NC}\n"
echo -e "${CYAN}2.1${NC} Trong project vừa tạo, vào:"
echo -e "    ${GREEN}APIs & Services > Library${NC}\n"
echo -e "${CYAN}2.2${NC} Search và enable các API sau:"
echo -e "    ✅ Google Sheets API"
echo -e "    ✅ Google Drive API"
echo ""

read -p "$(echo -e ${CYAN}Đã enable APIs? [Y/n]: ${NC})" CONFIRM3

# Step 3: Create Credentials
echo -e "\n${YELLOW}━━━ BƯỚC 3: Tạo Credentials ━━━${NC}\n"
echo -e "${CYAN}3.1${NC} Vào:"
echo -e "    ${GREEN}APIs & Services > Credentials${NC}\n"

echo -e "${CYAN}3.2${NC} Tạo API Key:"
echo -e "    - Click [+ CREATE CREDENTIALS]"
echo -e "    - Chọn [API Key]"
echo -e "    - Copy API Key"
echo ""

read -p "$(echo -e ${CYAN}Nhập API Key: ${NC})" API_KEY

echo -e "\n${CYAN}3.3${NC} Tạo OAuth 2.0 Client ID:"
echo -e "    - Click [+ CREATE CREDENTIALS]"
echo -e "    - Chọn [OAuth client ID]"
echo -e "    - Application type: [Web application]"
echo -e "    - Name: ${GREEN}MIA Dashboard${NC}"
echo -e "    - Authorized JavaScript origins:"
echo -e "      ${GREEN}http://localhost:5173${NC}"
echo -e "      ${GREEN}https://YOUR-DOMAIN.vercel.app${NC}"
echo -e "    - Click [CREATE]"
echo ""

read -p "$(echo -e ${CYAN}Nhập Client ID: ${NC})" CLIENT_ID
read -p "$(echo -e ${CYAN}Nhập Client Secret: ${NC})" CLIENT_SECRET

# Step 4: Create Spreadsheet
echo -e "\n${YELLOW}━━━ BƯỚC 4: Tạo Google Spreadsheet ━━━${NC}\n"
echo -e "${CYAN}4.1${NC} Mở Google Sheets:"
echo -e "    ${GREEN}https://sheets.google.com/${NC}\n"
echo -e "${CYAN}4.2${NC} Tạo spreadsheet mới với tên: ${GREEN}MIA-Dashboard-Data${NC}"
echo ""
echo -e "${CYAN}4.3${NC} Tạo các sheets sau:"
echo -e "    📊 ${GREEN}Orders${NC} - Dữ liệu đơn hàng"
echo -e "    📅 ${GREEN}Schedule${NC} - Lịch làm việc"
echo -e "    📦 ${GREEN}Inventory${NC} - Nhập hàng"
echo -e "    ⏰ ${GREEN}Overtime${NC} - Tăng ca"
echo -e "    🚛 ${GREEN}Logistics${NC} - Vận chuyển"
echo -e "    💰 ${GREEN}Costs${NC} - Chi phí"
echo ""
echo -e "${CYAN}4.4${NC} Copy Spreadsheet ID từ URL:"
echo -e "    URL: https://docs.google.com/spreadsheets/d/${YELLOW}SPREADSHEET_ID${NC}/edit"
echo ""

read -p "$(echo -e ${CYAN}Nhập Spreadsheet ID: ${NC})" SPREADSHEET_ID

# Step 5: Update .env
echo -e "\n${YELLOW}━━━ BƯỚC 5: Cập nhật Environment Variables ━━━${NC}\n"

if [ -f ".env" ]; then
    echo -e "${GREEN}Đang cập nhật file .env...${NC}"
    
    # Backup old .env
    cp .env .env.backup
    
    # Update .env
    cat > .env << EOF
# Google Sheets API - Generated by setup-google-sheets.sh
VITE_GOOGLE_API_KEY=${API_KEY}
VITE_GOOGLE_CLIENT_ID=${CLIENT_ID}
VITE_GOOGLE_CLIENT_SECRET=${CLIENT_SECRET}
VITE_SPREADSHEET_ID=${SPREADSHEET_ID}

# App Config
VITE_APP_NAME=MIA.VN Dashboard
VITE_APP_VERSION=1.0.0
EOF
    
    echo -e "${GREEN}✅ Đã cập nhật .env${NC}"
    echo -e "${YELLOW}⚠️  File .env cũ được backup tại: .env.backup${NC}"
else
    echo -e "${YELLOW}⚠️  File .env không tồn tại!${NC}"
    echo -e "Vui lòng chạy setup.sh trước"
    exit 1
fi

# Step 6: Setup Sample Data
echo -e "\n${YELLOW}━━━ BƯỚC 6: Thiết lập dữ liệu mẫu ━━━${NC}\n"
echo -e "${CYAN}Tạo cấu trúc dữ liệu cho từng sheet:${NC}\n"

echo -e "${GREEN}📊 Orders Sheet:${NC}"
echo -e "   A1: Date | B1: Channel | C1: Order ID | D1: Revenue | E1: Status"
echo ""

echo -e "${GREEN}📅 Schedule Sheet:${NC}"
echo -e "   A1: Date | B1: Employee | C1: Shift | D1: Hours | E1: Notes"
echo ""

echo -e "${GREEN}📦 Inventory Sheet:${NC}"
echo -e "   A1: Date | B1: Supplier | C1: Product | D1: Quantity | E1: Value | F1: Container"
echo ""

echo -e "${GREEN}⏰ Overtime Sheet:${NC}"
echo -e "   A1: Date | B1: Employee | C1: Hours | D1: Department | E1: Status"
echo ""

echo -e "${GREEN}🚛 Logistics Sheet:${NC}"
echo -e "   A1: Date | B1: Route | C1: Type | D1: Cost | E1: Products | F1: Status"
echo ""

echo -e "${GREEN}💰 Costs Sheet:${NC}"
echo -e "   A1: Month | B1: Category | C1: Amount | D1: Description | E1: Notes"
echo ""

# Step 7: Test Connection
echo -e "\n${YELLOW}━━━ BƯỚC 7: Test kết nối ━━━${NC}\n"

cat > test-sheets-connection.js << 'TESTEOF'
// Test Google Sheets connection
const SPREADSHEET_ID = process.env.VITE_SPREADSHEET_ID;
const API_KEY = process.env.VITE_GOOGLE_API_KEY;

async function testConnection() {
  try {
    const url = `https://sheets.googleapis.com/v4/spreadsheets/${SPREADSHEET_ID}?key=${API_KEY}`;
    const response = await fetch(url);
    const data = await response.json();
    
    if (data.spreadsheetId) {
      console.log('✅ Kết nối thành công!');
      console.log('📊 Spreadsheet:', data.properties.title);
      console.log('📄 Sheets:', data.sheets.map(s => s.properties.title).join(', '));
    } else {
      console.log('❌ Kết nối thất bại:', data.error?.message);
    }
  } catch (error) {
    console.log('❌ Lỗi:', error.message);
  }
}

testConnection();
TESTEOF

echo -e "${CYAN}Để test kết nối:${NC}"
echo -e "  ${GREEN}node test-sheets-connection.js${NC}\n"

# Step 8: Share Spreadsheet
echo -e "\n${YELLOW}━━━ BƯỚC 8: Chia sẻ Spreadsheet ━━━${NC}\n"
echo -e "${CYAN}Quan trọng: Chia sẻ spreadsheet với Service Account${NC}\n"
echo -e "1. Trong Google Sheets, click [Share]"
echo -e "2. Add email của Service Account (nếu có)"
echo -e "3. Hoặc set: ${GREEN}Anyone with the link can VIEW${NC}"
echo ""

read -p "$(echo -e ${CYAN}Đã chia sẻ spreadsheet? [Y/n]: ${NC})" CONFIRM4

# Summary
echo -e "\n${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}🎉 HOÀN TẤT SETUP GOOGLE SHEETS API!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"

echo -e "${CYAN}📋 Thông tin đã cấu hình:${NC}"
echo -e "  API Key: ${GREEN}${API_KEY:0:20}...${NC}"
echo -e "  Client ID: ${GREEN}${CLIENT_ID:0:30}...${NC}"
echo -e "  Spreadsheet ID: ${GREEN}${SPREADSHEET_ID}${NC}"
echo ""

echo -e "${CYAN}🔗 Quick Links:${NC}"
echo -e "  📊 Spreadsheet: ${GREEN}https://docs.google.com/spreadsheets/d/${SPREADSHEET_ID}/edit${NC}"
echo -e "  ⚙️  Console: ${GREEN}https://console.cloud.google.com/apis/dashboard?project=${NC}"
echo ""

echo -e "${YELLOW}⚠️  Lưu ý bảo mật:${NC}"
echo -e "  - KHÔNG commit file .env lên GitHub"
echo -e "  - Add credentials vào Vercel Environment Variables"
echo -e "  - Giữ API Key và Client Secret an toàn"
echo ""

echo -e "${CYAN}📚 Tài liệu tham khảo:${NC}"
echo -e "  - Google Sheets API: ${GREEN}https://developers.google.com/sheets/api${NC}"
echo -e "  - OAuth 2.0: ${GREEN}https://developers.google.com/identity/protocols/oauth2${NC}"
echo ""

echo -e "${GREEN}✅ Bạn có thể bắt đầu development với ./dev.sh${NC}\n"
